#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cmake
Version  : 3.6.1
Release  : 28
URL      : https://cmake.org/files/v3.6/cmake-3.6.1.tar.gz
Source0  : https://cmake.org/files/v3.6/cmake-3.6.1.tar.gz
Summary  : General purpose data compression library
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause BSD-4-Clause-UC GPL-2.0 MIT Zlib bzip2-1.0.5
Requires: cmake-bin
Requires: cmake-data
BuildRequires : cmake
BuildRequires : pkgconfig(expat)
BuildRequires : pkgconfig(libcurl)
BuildRequires : zlib-dev
Patch1: build.patch
Patch2: fix-x11.patch

%description
To create a cmake release, make sure the "release" tag is pointing to the
expected git commit:

%package bin
Summary: bin components for the cmake package.
Group: Binaries
Requires: cmake-data

%description bin
bin components for the cmake package.


%package data
Summary: data components for the cmake package.
Group: Data

%description data
data components for the cmake package.


%package dev
Summary: dev components for the cmake package.
Group: Development
Requires: cmake-bin
Requires: cmake-data
Provides: cmake-devel

%description dev
dev components for the cmake package.


%prep
%setup -q -n cmake-3.6.1
%patch1 -p1
%patch2 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484499961
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=%{_libdir} -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_RANLIB=/usr/bin/gcc-ranlib -DCMAKE_USE_SYSTEM_EXPAT=ON  -DCMAKE_USE_SYSTEM_CURL=on -DCMAKE_USE_SYSTEM_ZLIB=on
make VERBOSE=1  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1484499961
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/doc/cmake-3.6/Copyright.txt
/usr/doc/cmake-3.6/cmcompress/Copyright.txt
/usr/doc/cmake-3.6/cmlibarchive/COPYING
/usr/doc/cmake-3.6/cmliblzma/COPYING
/usr/doc/cmake-3.6/cmsys/Copyright.txt

%files bin
%defattr(-,root,root,-)
/usr/bin/cmake
/usr/bin/cpack
/usr/bin/ctest

%files data
%defattr(-,root,root,-)
/usr/share/cmake-3.6/*

%files dev
%defattr(-,root,root,-)
/usr/share/aclocal/*.m4
